server:
  port: 8092
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user
  registry:
    address: zookeeper://47.107.177.211:2181?backup=47.107.177.211:2182,47.107.177.211:2183


  